### ISSUE TITLE
Add chapters by URL

### ISSUE THREAD

**Issue by Ruriko** [fbg13/Clarity-Manga-Reader#3]
Is it possible to add chapter pictures by url instead of uploading pictures to server?

**Comment by f-b-g-m** [comment]
No.

I thought about it but i don't see any advantage in having it.

I am not aware of any site that will allow you hotlink their images.
Even if there are some, once you cause them big bandwidth usage they will block your site leaving you with broken images.

**Comment by Ruriko** [comment]
Aww it would of been nice for that feature to be added since I was thinking of uploading manga on cloud storage since they're cheaper to host on than a dedi server.

**Comment by f-b-g-m** [comment]
Do you mean things like amazon/google cloud storage?

**Comment by Ruriko** [comment]
yea like those similar services like Amazon, google etc...

**Comment by f-b-g-m** [comment]
That's not really how they're supposed to be used.
You use their API to upload the images to their server instead of your own, through the same means you upload to your server.
Like how you upload now in my plugin but the images end up on the cloud server (which you would set up in the settings).

I didn't work with this before so i'd have to look into it, but at the moment i don't really have the time.

Might add the way you mentioned, since it should be easier to implement.
